version: 2

project_name: bootstrapparrr

before:
  hooks:
    - go mod tidy

builds:
  - binary: bootstrapparrr
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0

archives:
  - formats: ['tar.gz']
    files:
      - CHANGELOG.md
      - LICENSE
    wrap_in_directory: true

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha256_checksums.txt"
  algorithm: sha256
