preset: angular
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/git"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - publishCmd: make release
  # - "@semantic-release/github"
