name: Build
'on':
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Lint, test and build
        run: |
          make lint
          make test
          make build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bootstrapparrr
          path: bootstrapparrr
          retention-days: 1

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create Github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
