name: Build
'on':
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Lint, test and build
        run: |
          make lint
          make test
          make build
